CREATE DATABASE easylearning_db WITH ENCODING UTF8;

CREATE ROLE easylearning_application WITH LOGIN PASSWORD '1234';

GRANT SELECT,INSERT,UPDATE,DELETE
ON ALL TABLES IN SCHEMA public
TO easylearning_application;

